### ISSUE TITLE
[Request] add support for additional CustomPaintings folders

### ISSUE THREAD

**Issue by ajsglist** [BoniatoRelleno/CustomPaintings#1]
in order to allow mod manager support/syncing to be as easy as possible, it would be great if CustomPaintings supported an alternate source of "CustomPaintings" folder from another mod (and ideally allowed for disabling the 8 base CustomPaintings images)

Thanks for the consideration

**Comment by BoniatoRelleno** [comment]
Hi! First of all, thanks for your suppport <3

Regarding your proposals, I will make a configuration file with an option to change the directory.

You already can delete the base images, them are only created the first time you open the game with the creation of the CustomPaintings directory.

**Comment by ajsglist** [comment]
>You already can delete the base images, them are only created the first time you open the game with the creation of the CustomPaintings directory.

Unfortunately, I don't think this level of control is available via mod manager.  Though it's possible I'm missing something.

**Comment by BoniatoRelleno** [comment]
If you are ussing r2modman you can do it anyway. Go to settings and click browse profile folder, then in the file explorer window go to BepInEx\plugins\CustomPaintings and delete the default images, now put in that folder the custom paintings that you want

**Comment by ajsglist** [comment]
Thanks for the update, now I see what you mean.

Unfortunately, I don't think this will sync between clients -- sharing a modmanager code will only pull the mod list and configs (unless I'm misunderstand that?)

No worries either way, I'm content waiting for an update that handles it directly.

Thanks again :)

**Comment by ajsglist** [comment]
In order to do that, wouldn't I need to essentially repack your mod with my own paintings?  If that's not what you're talking about, I'd love more information.

But if that's what you mean, I think my original post might be the best solution.  I can refer back to your release of CustomPaintings as a dependency while supplying the replacement paintings in a community pack (this is the same method used for other custom content -- suits, cosmetics, custom boombox tracks, etc).  Prevents any potential errors and makes using any updated versions of CustomPaintings a breeze.

**Comment by BoniatoRelleno** [comment]
That's what I mean, I understand that the problem is that the default paintings would continue being. I'll keep it in mind when making the configuration file, don't worry :)

**Comment by cfazilleau** [comment]
Hi ! I saw in the code of your plugin that you download the different images for the paintings using imgur URLs.
A suggestion I have is to move this to a config file, this way we could edit the links of the images we want the plugin to download, and also share it via code, as the config files are included when sharing by code.
Another line in the config file could be a boolean to force download the images at every launch, to ensure that everyone is up to date and prevent the mod from having to check the existing files everytime.
Tell me what you think about those ideas, I would gladly have done it myself and submitted a PR, but your code seems to be closed source

**Comment by BoniatoRelleno** [comment]
Hi, thanks for the ideas, I'm going to work on it right now :)

**Comment by cfazilleau** [comment]
Amazing ! I'll give it a try
