### ISSUE TITLE
[Bug] Custom paintings are not persistent when loading a save.

### ISSUE THREAD

**Issue by cfazilleau** [BoniatoRelleno/CustomPaintings#3]
When paintings are placed in the ship, quitting and reloading the save will reset all paintings to their default, vanilla texture.

**Comment by BoniatoRelleno** [comment]
Hi! It is a know bug, I will try to fix it in the future

**Comment by cfazilleau** [comment]
Any update on this ? If the code was open source I'd gladly contribute

**Comment by BoniatoRelleno** [comment]
Hi! Now that I finished the Ganimedes update I will continue with this mod :)
If you want to contribute you can look at the code in Thunderstore page and propose any additions but I like to work on my own mods so don't worry
