### ISSUE TITLE
[Suggestion] Use some kind of tag attached to save for loading paintings.

### ISSUE THREAD

**Issue by BurntFood** [BoniatoRelleno/CustomPaintings#5]
Idk if this is possible currently, but you could try saving something like a tag using the picture name or data like what minecraft's NBT does, so custom paintings load across saves.

Another thing you could try doing, is what suit saver does, and just have a text file with a list of the png file names that match to the amount of paintings saved on the ship.

For example of the text idea, you have 5 paintings on the ship, one default1.png, two default2.png, one default5.png, and one default7.png.

The text file could appear like so:
> host/save name:
> default1,default2,default2,default5,default7
>
> host/save name:
> etc...

Obviously clearing it when paintings are sold/lost, or you're ejected.

**Comment by BoniatoRelleno** [comment]
That's a good idea, I'm currently working on the next update of Ganimedes but when I finish it I'll try to do it, ty :)

**Comment by Vampire2008** [comment]
If you bussy maybe should open source code and some make the job and send to you a PR.

**Comment by Vampire2008** [comment]
@BoniatoRelleno, please open source code. I try to do modification myself.

**Comment by BoniatoRelleno** [comment]
I have published the project, sorry for the delay

**Comment by Vampire2008** [comment]
I possibly add this feature but I totaly rewrited source code. Also added support to loading images from mods installed via mod mangers and from mod that depends on LethalPainting.
I am planing to test with my friends, fix bugs and then create Pull Request.
You can view new code in my fork.

**Comment by BoniatoRelleno** [comment]
wow I've been looking at it and you've done a great job. If I understand correctly, you use the instance ID to identify each painting and you store it in a dictionary along with the texture index, is that instance ID the same when restarting the game? I didn't know about it.

To store the texture index you use the saveData of the grabbableObjects, I didn't know about that either, what class is it that manages it?

Thanks for your effort!

**Comment by BoniatoRelleno** [comment]
I actually think I found a bug in my other mod Ganimedes thanks to learning about saveData, I will have to try it. Ty!

**Comment by Vampire2008** [comment]
InstanceId is different bettween launches. It is Unity Id of object.
When game starts game loads stored object on ship. First object created then loaded it's data. So I can pair object with their texture index. Method `GrabbableObject.GetItemDataToSave` used to save data and to transfer data to clients. But it only for items on ship.
When round starts game spawn objects in complex on independed way on server and client uses same seed value. I also use level seed to generete new texture index and store it in dictionary to correctly save it on end of round.
But I have to test in long game.
I use dotPeek to decompile source code of game.

**Comment by Vampire2008** [comment]
Found some bugs with loading pictures. I have to fix them.
Also I should change saving method. Because when I enabled saving data for Painting it's requres to install mod for all client.

**Comment by Vampire2008** [comment]
I have created Pull Request #7. Waiting for your review. @BoniatoRelleno
