### ISSUE TITLE
Use the Painting's value to determine the texture shown

### ISSUE THREAD

**Issue by SeymourSchlong** [BoniatoRelleno/CustomPaintings#6]
This is a method I use in my own mod, and it guarantees that a) it will be synced between all clients and b) it will keep the same texture on reload, assuming the files don't change.

**Comment by BoniatoRelleno** [comment]
Oh thanks for the idea, do you know in which method the textures should be changed? I do it when the ship lands

**Comment by SeymourSchlong** [comment]
I patched it into the `SetScrapValue` method.

**Comment by BoniatoRelleno** [comment]
Thank you so much! I will try it
